###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Build Collector

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build collector
      run: |
        docker buildx build --push \
            --tag ghcr.io/avanderreest/infocollectormodule:latest \
            --platform linux/amd64,linux/arm64 .
 
