###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Build Collector

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build collector
      run: |
        docker build . -t ghcr.io/avanderreest/infocollectormodule:latest 
    - name: docker push
      run: |
        docker push ghcr.io/avanderreest/infocollectormodule:latest
